In [1]:
import numpy as np 

In [19]:
arr = np.array([2,4,5,6,7,6])

In [25]:
print(arr[1]+arr[3])

10


# reshape

In [20]:
new_arr = arr.reshape(2,3)

In [22]:
print(new_arr)

[[2 4 5]
 [6 7 6]]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


# 2d array 

In [13]:
arr1 = np.array([[2,3,4] ,[6,7,8]])

In [35]:
arr1[1,:2]

array([6, 7])

In [36]:
arr1

array([[2, 3, 4],
       [6, 7, 8]])

In [26]:
print(arr1[0,1])

3


# flatten array can change any dimension array to one D array 

In [23]:
flatten_arr1 = arr1.reshape(-1)

In [14]:
print(arr1)

[[2 3 4]
 [6 7 8]]


In [24]:
print(flatten_arr1)

[2 3 4 6 7 8]


#to tell the dimension of the array 

In [15]:
print(arr1.ndim)

2


# number of elements is the shape of array 

In [17]:
print(arr1.shape)

(2, 3)


# this means 2 rows and number of elements are 3 

# iterating 2D arrays

In [28]:
arr2 = np.array([[2,3,4] ,[6,7,8]])

In [30]:
for x in arr2:
    for y in x:
        print(y)

2
3
4
6
7
8


# slicing array [start:end:step] , step will skip the particular elements 

In [32]:
ar3 = np.array([2,4,5,6,7,6])

In [33]:
arr[1:5:2]

array([4, 6])

In [34]:
# it will skip the every alternate element as step is 2

# searching (printing elements which are even ) 

In [38]:
b = np.where(ar3%2 ==0 ) 
print(b)

(array([0, 1, 3, 5]),)


In [39]:
np.sort(ar3)

array([2, 4, 5, 6, 6, 7])

In [40]:
# for string it sort the array alphabetically 